// =========================================================================
// 도담 — 아이콘 헬퍼
// lucide-react 아이콘을 문자열 이름으로 매핑해, 데이터 상수에서 아이콘을
// 이름으로 지정할 수 있게 한다.  <Icon name="Wallet" size={20} />
// =========================================================================
import {
  Wallet,
  Gift,
  HandHeart,
  Stethoscope,
  Coins,
  Heart,
  Baby,
  Sparkles,
  ShieldCheck,
  GitCompare,
  MessageCircle,
  Target,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  Send,
  FileText,
  Search,
  SlidersHorizontal,
  ClipboardList,
  ClipboardCheck,
  Wand2,
  CircleCheck,
  CircleAlert,
  CircleHelp,
  Check,
  Plus,
  Pencil,
  Star,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  User,
  Bookmark,
  ListChecks,
  History,
  Phone,
  ExternalLink,
  Building2,
  MapPin,
  CalendarDays,
  Tag,
  Users,
  BadgeCheck,
  Trash2,
  Repeat,
  LogOut,
} from "lucide-react";

const MAP = {
  Wallet,
  Gift,
  HandHeart,
  Stethoscope,
  Coins,
  Heart,
  Baby,
  Sparkles,
  ShieldCheck,
  GitCompare,
  MessageCircle,
  Target,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  Send,
  FileText,
  Search,
  SlidersHorizontal,
  ClipboardList,
  ClipboardCheck,
  Wand2,
  CircleCheck,
  CircleAlert,
  CircleHelp,
  Check,
  Plus,
  Pencil,
  Star,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  User,
  Bookmark,
  ListChecks,
  History,
  Phone,
  ExternalLink,
  Building2,
  MapPin,
  CalendarDays,
  Tag,
  Users,
  BadgeCheck,
  Trash2,
  Repeat,
  LogOut,
};

export default function Icon({ name, size = 20, strokeWidth = 2, ...rest }) {
  const Cmp = MAP[name] || Sparkles;
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}
